import { Inter } from "next/font/google";
import "./globals.css";
import Leftsidebar from "./components/Leftsidebar";
import Rightsidebar from "./components/Rightsidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Dasboard Task",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex">

          <div className="w-1/6 general-shadow">
            <Leftsidebar/>
          </div>

        <div class="flex-1  text-white text-center">
        {children}
        </div>

        <div class="w-1/5 general-shadow">
          <Rightsidebar/>
        </div>

        </div>
        
        
        </body>
    </html>
  );
}
